# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test html
      run:
        echo 1111111test

    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with: 
        host: ${{secrets.UBUNTU_HOST}}
        user: ${{secrets.UBUNTU_USER}}
        pass: ${{secrets.UBUNTU_PASS}}
        scp: |
          ./test.html => /tmp
        last_ssh: |
          echo "ok...3"
          
        
